### ISSUE TITLE
Deprecation warnings due to set-output

### ISSUE THREAD

**Issue by hynek** [re-actors/alls-green#11]
GitHub has deprecated the set-output way, so I'm getting warnings in my workflows from alls-green.

Since they provided zero guidance how to fix it, I've written it down myself: https://hynek.me/til/set-output-deprecation-github-actions/

tldr: `echo "::set-output name=KEY::VALUE"` → `echo "KEY=VALUE" >>$GITHUB_OUTPUT`

**Comment by webknjaz** [comment]
Yeah, I've been meaning to fix this. Thanks for the issue!

**Comment by webknjaz** [comment]
@hynek FYI the actual docs section describing this is https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter. Not sure why they didn't link it directly...

**Comment by webknjaz** [comment]
@hynek they've later updated the blog post to include the examples: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples.

**Comment by hynek** [comment]
yeah they reached out to me
