### ISSUE TITLE
matrix job use case not covered or exemplified

### ISSUE THREAD

**Issue by ssbarnea** [re-actors/alls-green#5]
Apparently the current implementation does not count for matrix usage, thus not allowing you to ignore failure of one of matrix jobs.

Sadly GHA unfortunate naming makes it harder to even refer to individual job run as from the human point of view each entry inside checks is a job. But from GHA workflow definition that is not exactly the same thing as matrix job-definitions get expanded into multiple job-runs with potential different names.

How can we mark one particular matrix dimension as allowed to fail while still ensuring the the summarizing final "check" job does not fail?

Most projects will avoid using different definitions for each job-run and use matrix for them, as that prevents repeating a huge number of tasks. Thus we do need a practical solution for allowing one matrix-entry to fail.

**Comment by webknjaz** [comment]
Unfortunately, GitHub does not provide this level of detail through the `${{ needs }}` context. So it would not be possible to provide such a level of configuration for this on the level where this action is called.

I've learned, though, that if the matrix has a `continue-on-error` set up conditionally, then a failure status for such jobs does not influence the status of the whole matrix. I use this approach the CI setup of the Cheroot project, for example.

You are right, it's a great idea to document this case. It's a pity that we can't do anything else about it.

**Comment by ssbarnea** [comment]
Take a look at https://twitter.com/julian_dunn/status/1486147180473716737?s=20 - maybe we should take the opportunity to get this problem addressed by GHA team.

**Comment by webknjaz** [comment]
We could try but there's nothing else to do in this Action besides documenting the workaround which is probably enough. Even if they implement custom statuses, that will probably not require UX changes here.
